name: Deploy to Github pages

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Also run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: GOOS=js GOARCH=wasm go build -o ./web/wasm/app.wasm cmd/web/main.go

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with: 
          branch: gh-pages
          folder: web
