name: Deploy to Github pages

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Also run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install tinygo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.17.0/tinygo_0.17.0_amd64.deb
          sudo apt install ./tinygo_0.17.0_amd64.deb
          cp /usr/local/lib/tinygo/targets/wasm_exec.js ./web/js/wasm_exec.js

      - name: Build
        run: |
          mkdir ./web/wasm
          tinygo build -o ./web/wasm/app.wasm -target wasm --no-debug ./cmd/web/main.go

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with: 
          branch: gh-pages
          folder: web
